version: 2.1
# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run: 
          name: "Install dependencies"
          command: sudo npm install
      - run: 
          name: "React build"
          command: npm run build
  deploy:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run: 
          name: "Install Firebase"
          command: sudo npm install -g firebase-tools
      - run: 
          name: "Deploy to Firebase"
          command: firebase deploy
      - persist_to_workspace:
          root: /tmp/dir
          paths:
            - build/*

# Orchestrate our job run sequence
workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build